language: python
python:
  - '3.6'
services:
  - mongodb
  - docker
install:
  - pip3 install git+https://github.com/Maxmawt/INGInious
  - docker pull ingi/inginious-c-base
  - docker pull ingi/inginious-c-default
  - docker pull ingi/inginious-c-cpp
before_script:
  - python3 travis_setup.py
script:
  - inginious-autotest . LSINF1252 -l
